apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-app
  namespace: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-app
  template:
    metadata:
      labels:
        app: rabbit-app
    spec:
      containers:
        - name: rabbit
          image: chaitanyapasupula/rabbit-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rabbit-db:5432/rabbit
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbit-db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbit-db-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_FLYWAY_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-app
  namespace: rabbit
spec:
  type: ClusterIP
  selector:
    app: rabbit-app
  ports:
    - port: 8080
      targetPort: 8080
